import {Link} from '../../store';

export const links: Link[] = [
{
      brand: 'asus',
      model: 'strix',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438231.html',
    },
{
      brand: 'asus',
      model: 'tuf oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438230.html',
    },
{
      brand: 'asus',
      model: 'tuf',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438229.html',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438264.html',
    },
{
      brand: 'evga',
      model: 'ftw3',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438537.html',
    },
{
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438539.html',
    },
{
      brand: 'evga',
      model: 'xc3 black',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438543.html',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra hybrid',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00440781.html',
    },
{
      brand: 'evga',
      model: 'xc3',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438542.html',
    },
{
      brand: 'gainward',
      model: 'phoenix',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438243.html',
    },
{
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438260.html',
    },
{
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438262.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438269.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438258.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438279.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438259.html',
    },
{
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438516.html',
    },
{
      brand: 'inno3d',
      model: 'x3 oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438517.html',
    },
{
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438292.html',
    },
{
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438564.html',
    },
{
      brand: 'kfa2',
      model: 'sg oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438228.html',
    },
{
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438240.html',
    },
{
      brand: 'msi',
      model: 'suprim x',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438242.html  ',
    },
{
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438520.html',
    },
{
      brand: 'palit',
      model: 'gamerock oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438238.html',
    },
{
      brand: 'palit',
      model: 'gaming pro',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438241.html',
    },
{
      brand: 'palit',
      model: 'gamerock',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438263.html',
    },
{
      brand: 'zotac',
      model: 'amp holo',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438234.html',
    },
{
      brand: 'zotac',
      model: 'trinity',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438232.html',
    },
{
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080ti',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438233.html',
    }
];
