import {Link} from '../../store';

export const links: Link[] = [
{
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00400753.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00400753.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369072.html',
    },
{
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368579.html',
    },
{
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00375644.html',
    },
{
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368789.html',
    },
{
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368844.html',
    },
{
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369158.html',
    },
{
      brand: 'palit',
      model: 'gamerock oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00386332.html',
    },
{
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00375448.html',
    },
{
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369268.html',
    },
{
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369298.html',
    },
{
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368931.html',
    },
{
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368690.html',
    },
{
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368506.html',
    },
{
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00376207.html',
    },
{
      brand: 'evga',
      model: 'xc3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00398045.html',
    },
{
      brand: 'evga',
      model: 'xc3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00398045.html',
    },
{
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369303.html',
    },
{
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369265.html',
    },
{
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368968.html',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369299.html',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00398046.html',
    },
{
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00385535.html',
    },
{
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00375431.html',
    },
{
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368692.html',
    },
{
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368691.html',
    },
{
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00391624.html',
    },
{
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00375625.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00376208.html',
    },
{
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00368574.html',
    },
{
      brand: 'gainward',
      model: 'phantom',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00386063.html',
    },
{
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00391682.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00390466.html',
    },
{
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369094.html',
    },
{
      brand: 'msi',
      model: 'gaming z trio',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00423532.html',
    },
{
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00369150.html',
    },
{
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00386334.html',
    },
{
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00390727.html',
    },
{
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.ldlc.com/es-es/ficha/PB00438868.html',
    }
];
