import {Link} from '../../store';

export const links: Link[] = [
{
      brand: 'asus',
      model: 'strix white',
      series: '3080',
      url: 'https://xtremmedia.com/Asus_GeForce_ROG_Strix_White_RTX_3080_10GB_GDRR6X.html',
    },
{
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://xtremmedia.com/Asus_ROG_Strix_GeForce_RTX_3080_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://xtremmedia.com/Asus_ROG_Strix_GeForce_RTX_3080_Gaming_OC_10GB_GDDR6X.html',
    },
{
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://xtremmedia.com/Asus_TUF_GeForce_RTX_3080_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://xtremmedia.com/Asus_TUF_GeForce_RTX_3080_Gaming_OC_10GB_GDDR6X.html',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://xtremmedia.com/EVGA_GeForce_RTX_3080_FTW3_Ultra_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://xtremmedia.com/EVGA_GeForce_RTX_3080_XC3_Black_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://xtremmedia.com/EVGA_GeForce_RTX_3080_XC3_Ultra_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_Aorus_GeForce_RTX_3080_Xtreme_10G_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_Eagle_10GB_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_Eagle_OC_10GB_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_Gaming_OC_10GB_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'gaming oc waterforce wb',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_GAMING_OC_OC_WATERFORCE_WB_10GB_GDDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_MASTER_10GB_DDR6X.html',
    },
{
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://xtremmedia.com/Gigabyte_GeForce_RTX_3080_Vision_OC_10GB_GDDR6X.html',
    },
{
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://xtremmedia.com/Msi_GeForce_RTX_3080_Gaming_X_Trio_10GB_GDDR6X.html',
    },
{
      brand: 'msi',
      model: 'gaming z trio',
      series: '3080',
      url: 'https://xtremmedia.com/Msi_GeForce_RTX_3080_Gaming_Z_Trio_10GB_GDDR6X.html',
    },
{
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://xtremmedia.com/MSI_GeForce_RTX_3080_SUPRIM_X_10GB_GDDR6X.html',
    },
{
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://xtremmedia.com/Msi_GeForce_RTX_3080_Ventus_3X_OC_10GB_GDDR6X.html',
    },
{
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://xtremmedia.com/Palit_GeForce_RTX_3080_GameRock_10GB_GDDR6X.html',
    },
{
      brand: 'palit',
      model: 'gamerock oc',
      series: '3080',
      url: 'https://xtremmedia.com/Palit_GeForce_RTX_3080_GameRock_OC_10GB_GDDR6X.html',
    },
{
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://xtremmedia.com/Palit_GeForce_RTX_3080_GamingPro_10GB_GDDR6X.html',
    },
{
      brand: 'pny',
      model: 'xlr8 gaming',
      series: '3080',
      url: 'https://xtremmedia.com/PNY_GeForce_RTX_3080_EPIC_X_RGB_Triple_Fan_XLR8_Gaming_10GB_GDDR6X.html',
    },
{
      brand: 'pny',
      model: 'xlr8 gaming',
      series: '3080',
      url: 'https://xtremmedia.com/PNY_GeForce_RTX_3080_EPIC_X_RGB_Triple_Fan_XLR8_Gaming_10GB_GDDR6X_1.html',
    },
{
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://xtremmedia.com/Zotac_GeForce_RTX_3080_AMP_Holo_10GB_GDDR6X.html',
    },
{
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://xtremmedia.com/Zotac_GeForce_RTX_3080_Trinity_10GB_GDDR6X.html',
    },
{
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://xtremmedia.com/Zotac_GeForce_RTX_3080_Trinity_OC_10GB_GDDR6X.html',
    }
];
