import {Link} from '../../store';

export const links: Link[] = [
{
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1677326',
    },
{
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1677327',
    },
{
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1679872',
    },
{
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1687861',
    },
{
      brand: 'gainward',
      model: 'phantom',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684579',
    },
{
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684582',
    },
{
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684578',
    },
{
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1680777',
    },
{
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1768036',
    },
{
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1688819',
    },
{
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1681756',
    },
{
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1753794',
    },
{
      brand: 'inno3d',
      model: 'twin x2',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1681760',
    },
{
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1681768',
    },
{
      brand: 'msi',
      model: 'gaming z trio',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758122',
    },
{
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1765420',
    },
{
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758120',
    },
{
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1756007',
    },
{
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758701',
    },
{
      brand: 'gainward',
      model: 'phantom',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1780254',
    },
{
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758134',
    },
{
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1780260',
    },
{
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758192',
    },
{
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758698',
    },
{
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1758184',
    },
{
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1780508',
    },
{
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684564',
    },
{
      brand: 'palit',
      model: 'gamerock',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684571',
    },
{
      brand: 'palit',
      model: 'gamerock oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1684570',
    },
{
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1702466',
    },
{
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1679097',
    },
{
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.alternate.de/html/product/1771999',
    }
];
