/**
 * Product model type definitions
 */

/**
 * Specific product model identifiers
 */
export type Model =
  | 'test:model'
  | 'captcha-deterrent'
  | '5600x'
  | '5800x'
  | '5900x'
  | '5950x'
  | '600 gold'
  | '600 platinum'
  | '750 platinum'
  | '7800x3d'
  | '7950x'
  | '9600x'
  | '9700x'
  | '9800x3d'
  | '9900x'
  | '9950x'
  | '9950x3d'
  | 'a3 matx wd'
  | 'aero oc'
  | 'aero oc sff'
  | 'amd reference'
  | 'amp airo'
  | 'amp extreme airo'
  | 'amp extreme holo'
  | 'amp extreme infinity'
  | 'amp holo'
  | 'amp white'
  | 'aorus box'
  | 'aorus x wb'
  | 'aorus elite'
  | 'master ice'
  | 'aorus master 24g'
  | 'aorus master type-c'
  | 'aorus master'
  | 'aorus w'
  | 'aorus x wb'
  | 'aorus xtreme waterforce 24g'
  | 'aorus xtreme waterforce wb'
  | 'aorus xtreme waterforce'
  | 'aorus xtreme'
  | 'aorus'
  | 'astral lc'
  | 'astral oc'
  | 'astral'
  | 'b580'
  | 'battle-ax'
  | 'challenger oc'
  | 'challenger pro oc'
  | 'challenger pro'
  | 'challenger'
  | 'crosshair viii'
  | 'dream machine pro'
  | 'dream machine'
  | 'dream router'
  | 'dual fan'
  | 'dual mini oc'
  | 'dual mini'
  | 'dual oc'
  | 'dual'
  | 'eagle oc'
  | 'eagle'
  | 'ekwb'
  | 'epic x oc'
  | 'epic x'
  | 'ex gamer'
  | 'ex oc'
  | 'ex'
  | 'expert'
  | 'fighter'
  | 'founders edition'
  | 'ftw3 black'
  | 'ftw3 ultra hybrid'
  | 'ftw3 ultra hydro copper'
  | 'ftw3 ultra'
  | 'ftw3'
  | 'g4 doorbell pro'
  | 'gamerock oc'
  | 'gamerock'
  | 'gaming oc pro'
  | 'gaming oc waterforce wb'
  | 'gaming oc'
  | 'gaming pro oc'
  | 'gaming pro'
  | 'gaming trio oc white'
  | 'gaming trio oc'
  | 'gaming trio'
  | 'gaming verto epic-x'
  | 'gaming x slim'
  | 'gaming x trio'
  | 'gaming x'
  | 'gaming x3'
  | 'gaming z trio'
  | 'gaming'
  | 'ghost oc'
  | 'ghost'
  | 'hellhound white'
  | 'hellhound'
  | 'hurricane'
  | 'ice dragon super'
  | 'ichill frostbite'
  | 'ichill revolution'
  | 'ichill x3'
  | 'ichill x4'
  | 'ichill'
  | 'igame advanced'
  | 'igame advanced oc'
  | 'igame ultra oc'
  | 'igame ultra'
  | 'igame vulcan'
  | 'jetstream'
  | 'ko'
  | 'korax'
  | 'lhr'
  | 'master ultra oc'
  | 'nitro oc'
  | 'nitro+'
  | 'nitro'
  | 'nitro'
  | 'noise cancelling'
  | 'nx oc'
  | 'nx pro oc'
  | 'nx'
  | 'oc'
  | 'oc2'
  | 'overclocked'
  | 'ph'
  | 'phantom gs'
  | 'phantom gs'
  | 'phantom'
  | 'phoenix gs'
  | 'phoenix'
  | 'playstation 5 console'
  | 'playstation 5 digital edition'
  | 'pulse'
  | 'race oc'
  | 'raider'
  | 'red dragon'
  | 'red devil'
  | 'resogun'
  | 'reverb'
  | 'rgb'
  | 'rock oc'
  | 'rogstrixoc'
  | 'sf'
  | 'sg oc'
  | 'sg'
  | 'single fan'
  | 'strix lc'
  | 'strix oc'
  | 'strix oc white'
  | 'strix'
  | 'suprim liquid x'
  | 'suprim liquid'
  | 'suprim x'
  | 'suprim'
  | 'surge'
  | 'taichi'
  | 'tdp'
  | 'trinity oc'
  | 'trinity white'
  | 'trinity'
  | 'tuf gaming oc'
  | 'tuf gaming'
  | 'tuf oc'
  | 'tuf'
  | 'turbo'
  | 'turoque'
  | 'twin edge oc'
  | 'twin edge white'
  | 'twin edge'
  | 'twin fan'
  | 'twin x2 oc'
  | 'twin x2'
  | 'udm pro'
  | 'udm'
  | 'udr'
  | 'ultra'
  | 'unvr pro'
  | 'unvr'
  | 'uprising'
  | 'ventus 2x oc'
  | 'ventus 2x'
  | 'ventus 3x e1 oc'
  | 'ventus 3x oc plus'
  | 'ventus 3x oc white'
  | 'ventus 3x oc'
  | 'ventus 3x'
  | 'vetro'
  | 'vision oc'
  | 'vision'
  | 'windforce oc'
  | 'windforce oc sff'
  | 'windforce v2'
  | 'windforce'
  | 'x trio'
  | 'x3 oc'
  | 'x3w'
  | 'xbox series s'
  | 'xbox series x'
  | 'xc black'
  | 'xc gaming'
  | 'xc3 black'
  | 'xc3 ultra hybrid'
  | 'xc3 ultra'
  | 'xc3'
  | 'xlr8 epic x'
  | 'xlr8 gaming uprising epic x'
  | 'xlr8 gaming'
  | 'xlr8 revel epic x'
  | 'xlr8 revel'
  | 'xlr8 uprising'
  | 'xlr8 verto epic x oc'
  | 'xlr8 verto epic x'
  | 'xlr8 verto oc'
  | 'xlr8 verto'
  | 'xlr8'
  | 'xtreme';
